### ISSUE TITLE
Privilege for Administration area missing when analyser role is assigned and user is not admin

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.ContentRepository.Debugger#38]
```yaml
  'Shel.ContentRepository.Debugger:NodeTypesAnalyzer':
    privileges:
      - privilegeTarget: 'Neos.Neos:Backend.Module.Administration'
        permission: GRANT
```
